In [1]:
import numpy as np

In [2]:
# Creating arrays with arange
# arange equal to range
a = np.arange(5, dtype=float)
print(a)
a = np.arange(1, 6, 2, dtype=int)
print(a)

[0. 1. 2. 3. 4.]
[1 3 5]


In [3]:
# To create a square matrix with a main diagonal
# filled with 1's, use the identity method
a = np.identity(4, dtype=float)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# Math operations with arrays
a = np.array([1, 2, 3], float)
b = np.array([5, 2, 6], float)
print(a)
print(b)

[1. 2. 3.]
[5. 2. 6.]


In [5]:
# add
print(a + b)

[6. 4. 9.]


In [6]:
# sub
print(a - b)

[-4.  0. -3.]


In [7]:
# mul
print(a * b)

[ 5.  4. 18.]


In [8]:
# div
print(a / b)

[0.2 1.  0.5]


In [9]:
# remainder of the division
print(a % b)

[1. 0. 3.]


In [10]:
# pow
print(b ** a)

[  5.   4. 216.]


In [11]:
# For two-dimensional arrays, multiplication remains 
# element-wise and does not correspond to matrix multiplication
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)

print(a * b)

[[ 2.  0.]
 [ 3. 12.]]


In [12]:
# Errors are thrown if the size does not match.
a = np.array([1,2,3], float)
b = np.array([4,5], float)
print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
# However, if the dimensions of the arrays do not match, 
# they will be converted to perform mathematical operations. 
# This often means that the smaller array will be used 
# multiple times to complete operations.
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print(a, "\n")
print(b, "\n")
print(a + b)

[[1. 2.]
 [3. 4.]
 [5. 6.]] 

[-1.  3.] 

[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [14]:
# In addition to the standard operators, numpy includes a library 
# of standard mathematical functions that can be applied element-wise 
# to arrays. Functions proper: abs, sign, sqrt, 
# log, log10, exp, sin, cos, tan, arcsin, arccos, 
# arctan, sinh, cosh, tanh, arcsinh, arccosh, and arctanh.
a = np.array([1, 4, 9], float)
np.sqrt(a)

array([1., 2., 3.])

In [15]:
# The floor, ceil, and rint functions return the bottom, 
# top, or nearest (rounded) value.
a = np.array([1.1, 1.5, 1.9], float)
print(np.floor(a), "\n")
print(np.ceil(a), "\n")
print(np.rint(a), "\n")

[1. 1. 1.] 

[2. 2. 2.] 

[1. 2. 2.] 



In [16]:
# Also included in numpy are two important mathematical constants
print(np.e)
print(np.pi)

2.718281828459045
3.141592653589793


In [17]:
# Loops on arrays
a = np.array([1, 4, 5], int)
for x in a:
    print(x)

1
4
5


In [18]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print (x)

[1. 2.]
[3. 4.]
[5. 6.]


In [19]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for (x, y) in a:
    print(x * y)

2.0
12.0
30.0


In [ ]:
# Basic operations on arrays

In [20]:
# Elements can be summed or multiplied
a = np.array([2, 4, 3], float)
print(a.sum())
print(a.prod())

9.0
24.0


In [21]:
# Like lists, arrays can be sorted
a = np.array([6, 2, 5, -1, 0], float)
print(sorted(a))
a.sort()
print(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]
[-1.  0.  2.  5.  6.]


In [34]:
# Values in an array can be "shortened" to belong to a given range
a = np.array([6, 2, 5, -1, 0], float)
print(a.clip(0, 5))

[5. 2. 5. 0. 0.]


In [23]:
# Unique elements can be retrieved like this
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
print(np.unique(a))

[1. 4. 5. 7.]


In [24]:
# For two-dimensional arrays, the diagonal can be obtained as follows
a = np.array([[1, 2], [3, 4]], float)
print(a.diagonal())

[1. 4.]


In [ ]:
# Comparison operators and value testing

In [25]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)

print(a > b)
print(a == b)
print(a <= b)

[ True False False]
[False  True False]
[False  True  True]


In [26]:
c = a > b
print(c)

[ True False False]


In [27]:
# Arrays can be compared to a single value
a = np.array([1, 3, 0], float)
print(a > 2)

[False  True False]


In [28]:
# Boolean arrays can be used as arrays for filtering
a = np.array([[6, 4], [5, 9]], float)
print(a >= 6)
print(a[a >= 6])

[[ True False]
 [False  True]]
[6. 9.]


In [29]:
# NumPy provides many functions for working 
# with vectors and matrices. The dot function returns 
# the dot product of vectors
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
print(np.dot(a, b))

5.0


In [30]:
# The dot function can also multiply matrices
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)

print(np.dot(b, a), "\n")
print(np.dot(a, b), "\n")
print(np.dot(a, c), "\n")
print(np.dot(c, a), "\n")

[ 6. 11.] 

[ 3. 13.] 

[[ 4.  0.]
 [14.  2.]] 

[[2. 4.]
 [0. 4.]] 



In [31]:
# NumPy also provides a set of built-in functions and methods for working 
# with linear algebra. All this can be found in the linalg sub-module. 
# These modules can also be operated on degenerate and non-degenerate matrices. 
#The determinant of the matrix is found in this way
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
print(a, "\n")
print(np.linalg.det(a))

[[4. 2. 0.]
 [9. 3. 7.]
 [1. 2. 1.]] 

-48.00000000000003


In [32]:
# You can also find the eigenvector and eigenvalue of a matrix
# собственный вектор и собственное значение матрицы
vals, vecs = np.linalg.eig(a)
print(vals, "\n")
print(vecs, "\n")

[ 8.85591316  1.9391628  -2.79507597] 

[[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]] 



In [33]:
# A non-singular matrix can be found like this
b = np.linalg.inv(a)
print(b, "\n")
print(np.dot(a, b))

[[ 0.22916667  0.04166667 -0.29166667]
 [ 0.04166667 -0.08333333  0.58333333]
 [-0.3125      0.125       0.125     ]] 

[[1.00000000e+00 5.55111512e-17 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.38777878e-17 1.00000000e+00]]
