In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
# 1d array
a = np.array([1, 2, 3, 4, 5], float)

In [4]:
print(a)
print(type(a))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [5]:
print(a[:2])
print(a[3])
a[0] = 5
print(a)


[1. 2.]
4.0
[5. 2. 3. 4. 5.]


In [ ]:
# 2d array
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(a[1, 0]) # a[1][0]

[[1. 2. 3.]
 [4. 5. 6.]]
4.0


In [9]:
print(a[1, :])
print(a[:, 2])
print(a[-1:, -2:])

[4. 5. 6.]
[3. 6.]
[[5. 6.]]


In [11]:
print(a.shape) # returns the number of rows and columns (2, 3)

print(a.dtype) # return data type in array


(2, 3)
float64


In [12]:
# Reformat 1d array to 2d array with numpy
a = np.array(range(10), float)
print(a)
a = a.reshape((5, 2))
print(a)
print(a.shape) # Reshape create new array

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
(5, 2)


In [13]:
# np array to list
a = np.array(range(10), float)
print(a)
print(a.tolist())
print(list(a))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


In [14]:
# Filling an array with the same value
a = np.array([1, 2, 3], float)
print(a)
a.fill(0)
print(a)


[1. 2. 3.]
[0. 0. 0.]


In [15]:
# Transposing arrays is also possible, creating a new array
a = np.array(range(6), float).reshape((2, 3))
print(a)
print(a.transpose())

[[0. 1. 2.]
 [3. 4. 5.]]
[[0. 3.]
 [1. 4.]
 [2. 5.]]


In [16]:
# 2d arr to 1d
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(a.flatten())

[[1. 2. 3.]
 [4. 5. 6.]]
[1. 2. 3. 4. 5. 6.]


In [17]:
# Arrays concat
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
new = np.concatenate((a, b, c))
print(new)


[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [18]:
# Matrix with ones
ones = np.ones((2,3), dtype=float)
print(ones)
ones = np.ones(2, dtype=float)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Matrix with zeros
zeros = np.zeros(7, dtype=float)
print(zeros)
zeros = np.zeros((5, 5), dtype=float)

[0. 0. 0. 0. 0. 0. 0.]


In [20]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
# To zeros or to ones
onesB = np.ones_like(b)
print(onesB)
zerosA = np.zeros_like(a)
print(zerosA)


[1. 1. 1. 1.]
[0. 0.]


In [21]:
# To ones
onesB = np.ones_like(b)
print(onesB)

[1. 1. 1. 1.]


In [22]:
# To zeros
zerosA = np.zeros_like(a)
print(zerosA)

[0. 0.]


In [ ]:
# Python list vs numpy ndarray benchmark

In [23]:
elements_count = 10
# Python list
x_list = [x for x in range(elements_count)]
y_list = [(y*2) for y in range(elements_count)]

print(x_list)
print(y_list)

# Numpy array
x_array = np.array(x_list)
y_array = np.array(y_list)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [24]:
%%timeit    # jupiter magic command
result = []
for i in range(len(x_list)):
    result.append(x_list[i] + y_list[i])
# print(result)

1.96 µs ± 18.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [25]:
%%timeit
result = x_array + y_array
# print(result)

745 ns ± 18.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [26]:
list_time = 1.96e-6 # ms -> 0.0e-6, ns 0.0e-9 
array_time = 745e-9
print(round(list_time / array_time, 1), "slower")

2.6 slower


In [27]:
elements_count = 1000
# Python list
x_list = [x for x in range(elements_count)]
y_list = [(y*2) for y in range(elements_count)]

# print(x_list)
# print(y_list)

# Numpy array
x_array = np.array(x_list)
y_array = np.array(y_list)

In [28]:
%%timeit    # jupiter magic command
# Python list

result = []
for i in range(len(x_list)):
    result.append(x_list[i] + y_list[i])
# print(result)

176 µs ± 6.42 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [29]:
%%timeit
# Numpy array

result = x_array + y_array
# print(result)

1.47 µs ± 244 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [30]:
list_time = 176e-6 # ms -> 0.0e-6, ns 0.0e-9 
array_time = 1.47e-6
print(round(list_time / array_time, 1), "slower")

119.7 slower
